"""Outtlyr Data Selection Module.

Hypothesis-driven link extraction pipeline. Replaces the legacy
`services/link_farming.py` once milestones land end-to-end.

Public surface (Step 1):
    TimeWindow, TypedQuery, ChannelFit, RawResult,
    DiscoveredLink, ShortVideoLink,
    plus channel/archetype taxonomies.
"""
from __future__ import annotations

from .cost_meter import (
    CostLimitExceeded,
    CostMeter,
    JobCostEntry,
    current_job_id,
    default_cost_cap_usd,
    get_meter,
    reset_current_job,
    reset_meter,
    set_current_job,
)
from .decomposer import Decomposition, decompose
from .dedup import (
    LinkCluster,
    canonical_url,
    cluster_links,
    cluster_stats,
    content_hash,
    propagate_verdicts_to_members,
    representatives,
)
from .discoverers import (
    Discoverer,
    GooglePAADiscoverer,
    MarketplaceDiscoverer,
    NewsDiscoverer,
    QuoraDiscoverer,
    RedditDiscoverer,
    ShortVideoDiscoverer,
    SubstackDiscoverer,
    TikTokDiscoverer,
    YouTubeDiscoverer,
    YouTubeShortsDiscoverer,
    get_google_paa,
    get_marketplace,
    get_news,
    get_quora,
    get_reddit,
    get_substack,
    get_tiktok,
    get_youtube,
    get_youtube_shorts,
)
from .query_synthesizer import (
    CHANNEL_ARCHETYPES,
    MAX_QUERIES_PER_CHANNEL,
    synthesize_pair_pooled,
    synthesize_queries,
)
from .triage import (
    BATCH_SIZE,
    BODY_CHAR_BUDGET,
    MAX_TRIAGE_PER_HYPOTHESIS,
    TriageContext,
    build_context,
    group_by_verdict,
    triage,
)
from .orchestrator import (
    DiscovererRegistry,
    PipelineEvent,
    PipelineResult,
    default_registry,
    run_pipeline,
)
from .job_runner import (
    JobState,
    await_completion,
    clear_jobs,
    create_job,
    get_job,
    list_jobs,
    subscribe,
)
from .csv_io import (
    ParseError,
    ParsedBatch,
    ParsedHypothesis,
    parse_hypothesis_csv,
    preview_summary,
)
from .batch_runner import (
    BATCH_CONCURRENCY,
    BatchMember,
    BatchState,
    await_batch_completion,
    clear_batches,
    create_batch,
    get_batch,
    list_batches,
    subscribe_batch,
)
from .source_selector import get_all_channel_scores, score_channels
from .trends_seed import (
    batch_rising_queries,
    fetch_related_topics,
    fetch_rising_queries,
    geo_from_hints,
    interest_over_time,
    normalize_geo,
)
from .models import (
    ARCHETYPE_NAMES,
    CHANNEL_IDS,
    SHORT_VIDEO_CHANNELS,
    Archetype,
    ChannelFit,
    ChannelId,
    DiscoveredLink,
    QueryVertical,
    RawResult,
    ShortVideoLink,
    TimeWindow,
    TypedQuery,
    Verdict,
    WindowLabel,
)

__all__ = [
    "ARCHETYPE_NAMES",
    "CHANNEL_IDS",
    "SHORT_VIDEO_CHANNELS",
    "Archetype",
    "ChannelFit",
    "ChannelId",
    "Decomposition",
    "DiscoveredLink",
    "QueryVertical",
    "RawResult",
    "ShortVideoLink",
    "TimeWindow",
    "TypedQuery",
    "Verdict",
    "WindowLabel",
    "BATCH_CONCURRENCY",
    "BATCH_SIZE",
    "BODY_CHAR_BUDGET",
    "BatchMember",
    "BatchState",
    "CHANNEL_ARCHETYPES",
    "MAX_QUERIES_PER_CHANNEL",
    "MAX_TRIAGE_PER_HYPOTHESIS",
    "ParseError",
    "ParsedBatch",
    "ParsedHypothesis",
    "CostLimitExceeded",
    "CostMeter",
    "Discoverer",
    "DiscovererRegistry",
    "GooglePAADiscoverer",
    "JobCostEntry",
    "JobState",
    "LinkCluster",
    "MarketplaceDiscoverer",
    "NewsDiscoverer",
    "PipelineEvent",
    "PipelineResult",
    "QuoraDiscoverer",
    "RedditDiscoverer",
    "ShortVideoDiscoverer",
    "SubstackDiscoverer",
    "TikTokDiscoverer",
    "TriageContext",
    "YouTubeDiscoverer",
    "YouTubeShortsDiscoverer",
    "await_batch_completion",
    "await_completion",
    "batch_rising_queries",
    "build_context",
    "canonical_url",
    "clear_batches",
    "clear_jobs",
    "cluster_links",
    "cluster_stats",
    "content_hash",
    "current_job_id",
    "default_cost_cap_usd",
    "create_batch",
    "create_job",
    "decompose",
    "default_registry",
    "fetch_related_topics",
    "fetch_rising_queries",
    "geo_from_hints",
    "get_all_channel_scores",
    "get_batch",
    "get_google_paa",
    "get_meter",
    "get_job",
    "get_marketplace",
    "get_news",
    "get_quora",
    "get_reddit",
    "get_substack",
    "get_tiktok",
    "get_youtube",
    "get_youtube_shorts",
    "group_by_verdict",
    "interest_over_time",
    "list_batches",
    "list_jobs",
    "normalize_geo",
    "parse_hypothesis_csv",
    "preview_summary",
    "propagate_verdicts_to_members",
    "representatives",
    "reset_current_job",
    "reset_meter",
    "run_pipeline",
    "set_current_job",
    "score_channels",
    "subscribe",
    "subscribe_batch",
    "synthesize_pair_pooled",
    "synthesize_queries",
    "triage",
]
